name: Code Review and Linting

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  lint-and-review:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      # Get dependencies
      - name: Get dependencies
        run: flutter pub get

      # Run Dart analysis
      - name: Run Dart Analysis
        run: dart analyze

      # Check Dart Formatting
      - name: Check Dart Formatting
        run: dart format --set-exit-if-changed .

      # Run ChatGPT Code Review
      - name: Run ChatGPT Code Review
        uses: anc95/ChatGPT-CodeReview@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: Korean
          exclude: "**/*.json, **/*.md, yarn, lock, dist/**"
    